__tests__/mardown-converter/fixtures/double_underscores.html, __tests__/mardown-converter/fixtures/double_underscores.md, __tests__/mardown-converter/html-markdown.ts, __tests__/mardown-converter/markdown-html.ts, src/components/block-editable/BlockEditable.js, src/core/markdown-converter.ts, src/core/string.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/3)
=> Added Implementation For Rendering Html Raw

src/components/actions/Actions.js, src/components/document-translatable/DocumentTranslatable.js, src/components/section-translatable/SectionTranslatable.js, src/components/translatable/Translatable.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/4)
=> Add blockable functionality - initial commit

package.json, src/components/actions/Actions.js, src/core/localStrings.js
Tooltips added to actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/5)
=> Feature cn tooltips

src/components/block-editable/BlockEditable.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/7)
=> Bug fix for tc-create save refresh #120

package.json, src/components/block-editable/BlockEditable.js, src/components/document-translatable/DocumentTranslatable.js, src/components/section-translatable/SectionTranslatable.js, src/components/translatable/Translatable.js, src/core/itemsReducer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/9)
=> Fix For Save Button Not Showing on Blur

src/components/block-editable/BlockEditable.js, src/components/block-editable/README.md
Let's please merge this branch -- it replaces the earlier one with similar name.
Apologies -- I was not testing the correct version of the component in the app.  This change fixes the issue #120.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/8)
=> Bug fix tc-create-app #120 saving issue onBlur

src/components/block-editable/BlockEditable.js, src/components/block-editable/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/10)
=> Resolving merge conflict from PR #9

package.json
v1.0.2-rc.2 -- corrected version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/12)
=> v1.0.2-rc.2

.vscode/launch.json, __tests__/mardown-converter/html-markdown.ts, package.json, src/components/translatable/README.md, src/core/markdown-converter.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/19)
=> bold-italic fix

src/components/block-editable/BlockEditable.js, src/components/block-editable/helpers.js, tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/25)
=> Clear Text On Paste

.gitignore, src/components/block-editable/BlockEditable.js, src/components/block-editable/helpers.js, src/components/translatable/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/27)
=> Fix Format Strip On Paste

package.json, src/components/block-editable/BlockEditable.js, src/components/block-editable/README.md, src/components/block-editable/helpers.js, src/core/markdown-converter.ts, src/core/string.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32)
=> Fix Markdown Editor Issues

src/components/block-editable/README.md, src/core/markdown-converter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/34)
=> WIP : just comparing branches

src/core/markdown-converter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/33)
=> Zach easy blockquote 321

package.json, src/components/Markdown.context.js, src/components/block-editable/BlockEditable.js, src/components/block-editable/README.md, src/components/block-editable/useStyles.js, src/components/block-translatable/BlockTranslatable.js, src/components/document-translatable/DocumentTranslatable.js, src/components/index.js, src/components/section-translatable/README.md, src/components/section-translatable/SectionTranslatable.js, src/components/translatable/README.md, src/components/translatable/Translatable.js, src/core/itemsReducer.ts, src/core/markdown-converter.ts, src/core/markdown.ts, src/core/string.ts, yarn.lock
Rolling back markdown-translatable
and adding in "good" fixes from along the way
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/38)
=> Rolling back markdown-translatable

src/core/markdown-converter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/40)
=> Fix non-breaking space

src/components/block-editable/BlockEditable.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/44)
=> 597 MD double spaces onEdit

src/components/block-editable/BlockEditable.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/46)
=> Bug zach 597 backspace key down save

package.json, src/core/markdown-converter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/48)
=> disable source links or open in new window

package.json, src/components/translatable/Translatable.js, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/51)
=> Markdown header

src/components/document-translatable/README.md, src/components/translatable/README.md, src/core/markdown-converter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/58)
=> Fix UL list format

src/components/block-editable/BlockEditable.js
added id to elements in Blockeditable
for eg: data-test="blockeditable-editable-markdown-pre"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/markdown-translatable/77)
=> Feature jincy cypress test

.github/workflows/nodejs.yml, __tests__/mardown-converter/fixtures/hyperlink.html, __tests__/mardown-converter/markdown-html.ts, package.json
Fix github actions so they actually work.
Also includes a fix in the code so the tests pass.
Updated the config slightly to use the latest versions
Also switched to ubuntu instead of macos because it finishes in 1 min instead of 3 mins.
=> Fix github action by using lts node

src/components/block-translatable/BlockTranslatable.js, src/components/document-translatable/DocumentTranslatable.js, src/components/section-translatable/SectionTranslatable.js, src/components/translatable/Translatable.js
Used by https://github.com/unfoldingWord/tc-create-app/pull/1407
=> Add prop to show custom fonts
